### ISSUE TITLE
An error of bft time example

### ISSUE THREAD

**Issue by xiangjianmeng** [tendermint/spec#111]
The result of [bft time](https://github.com/tendermint/spec/blob/master/spec/consensus/bft-time.md) example is not equal to that of calculating through function of [WeightedMedian](https://github.com/tendermint/tendermint/blob/3c79251ffc93d4653e42083c20c6d62c4a177efa/types/time/time.go#L35). The result is `500` not `98` after calling this function with the values of example above.

**Comment by ebuchman** [comment]
Are you passing in `50` or `70` for the total voting power? The argument name `totalVotingPower` in the implementation is a bit misleading because it's not the voting power of the whole validator set, but of those that were included in the the LastCommit. This gets computed in [state.MedianTime](https://github.com/tendermint/tendermint/blob/master/state/state.go#L266) . So in this case it would use `50` as totalVotingPower, and when run with that it returns 98.

**Comment by cmwaters** [comment]
Closing this issue as BFT time has been replaced with Proposer Based Timestamps (PBTS)
