### ISSUE TITLE
DuplicateVoteEvidence should be valid even if Vote.ValidatorIndex does not match

### ISSUE THREAD

**Issue by ebuchman** [tendermint/spec#116]
According to the [spec] and the [Go impl], both Votes in a DuplicateVoteEvidence must also have the same Vote.ValidatorIndex (position of the validator in the validator set). However this would only be true if the validator sets for the respective blocks being signed were the same, or had the same order, which might be the case for the full node, but not necessarily for the light client.  

So I think we need to remove the requirement that the ValidatorIndex matches

[spec]: https://github.com/tendermint/spec/blob/master/spec/blockchain/blockchain.md#evidence-1
[Go impl]: https://github.com/tendermint/tendermint/blob/master/types/evidence.go#L287

**Comment by cmwaters** [comment]
I tend to agree. 

I think the only characteristic that using the index brings for the full node, is that if there is a fork then in subsequent blocks where the validator sets diverge, the node won't consider DuplicateVoteEvidence if a node in both sets signs for two blocks in either of the forks. Whereas omitting the check would mean that we would still produce evidence.

As it stands for the light client, because it will most likely be that the conflicting header isn't the header with the common ancestor, an attempt to detect a full fork will most likely fail detection because the validator sets could at the height of the conflicting headers be different. 

I guess looking from the other angle, I can't see a situation where removing this check will allow for "honest" behaving nodes to be framed with DuplicateVoteEvidence

Last thing I wanted to note is that AmnesiaEvidence also has the same check

**Comment by ebuchman** [comment]
Should we fix this for v0.34 tendermint?

**Comment by cmwaters** [comment]
I will open an issue in the go tendermint repo. It should be just a few line change to get it done so I don't see why not

**Comment by marbar3778** [comment]
could you add validation rules to the evidence section in data_structures? This is missing for all evidence.
