### ISSUE TITLE
Selective Broadcast

### ISSUE THREAD

**Issue by marbar3778** [tendermint/spec#189]
## Problem definition

Reactors/modules may need specific data to a block, but not the entire block. Currently, the blockchain reactor sends the entire block to the peer, but there is the potential other reactors/modules will want to use the blockchain reactor to request data. 

For example the light client would need to request enough data to build a light block, but not the entire block. 

## Proposal

Define a protocol that a peer can send a request for information at a specific height. A simple approach would be something like graphql. If a field in the block is set to true the peer will send it. 

```proto
message DataRequest {
	uint64 height = 1;
	BlockData block_data = 2;
}

message BlockData {
	bool header = 1;
	bool data = 2;
	bool lastCommit = 3;
	bool evidence = 4;
}
```

More granularity into block fields could be added if needed.

### Reference

https://arxiv.org/abs/2010.00217 section 4

**Comment by cmwaters** [comment]
As far as the P2P layer is concerned we have a channel for sending `LightBlocks`, `Blocks` and `Evidence`. I'm not sure if there needs to be any changes made to accommodate any other needs within Tendermint. I do think that we should eventually look to structure the blockstore to store `Header`, `Commit`, `Evidence` and `Data` separately instead of in `Parts` as statesync, blocksync and RPC are the most common use cases. However this is a separate issue. I'm going to close this for now.
