### ISSUE TITLE
blockparams: introduce an epoch_duration field

### ISSUE THREAD

**Issue by marbar3778** [tendermint/spec#260]
# Protocol Change Proposal

## Summary

Many applications will use epochs to track and execute validator set changes. While an app does this tendermint still assumes a validator set change will occur on every block. 

## Problem Definition

Not a problem but an optimization

## Proposal

Introduce a field in `blockparams`  that tells tendermint how many blocks are in an epoch. 

```proto
message BlockParams {
  // Max block size, in bytes.
  int64 max_bytes = 1;
  // Max gas per block.
  // Note: must be greater or equal to -1
  int64 max_gas = 2;
  // duration of an epoch, setting to 1 means validator sets can change every block
  ++ uint64 epoch_duration = 4; ++
}
```

This can lead to optimizations in tendermint because we are now aware of when to call specific logic to handle validator set changes. Light clients verification will become more efficient as we are aware when validator set changes occur. 

see https://github.com/tendermint/tendermint/issues/5260 for previous discussions
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
Would like to hear thoughts on this from @alexanderbez and @ebuchman. They had thoughts on this in the previous issue.

**Comment by josef-widder** [comment]
What is the envisioned interface to the applications regarding punishment. Is punishment happening within epochs? Is it in the responsibility of the applications to figure out the validator set has changed due to misbehavior?

**Comment by alexanderbez** [comment]
> While an app does this tendermint still assumes a validator set change will occur on every block.

Specifically, the validator set _can_ change, not necessarily will. I imagine the most common thing that happens during each block is power mutations, not membership mutations.

@josef-widder you can find the original discussion with motivation [here](https://github.com/cosmos/cosmos-sdk/discussions/8328) and the resulting ADR [here](https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-039-epoched-staking.md).

----

@marbar3778 I support this idea, but I would like to know the interplay between this new field and the application. Specifically, in order to handle epoch-based staking, w/ epoch > 1, it is entirely up to the application to handle this in the way it deems most secure and performant.

Can you describe the interplay between this field and say how an `x/staking` module would use it?

/cc @sunnya97 @ValarDragon

**Comment by marbar3778** [comment]
> Specifically, in order to handle epoch-based staking, w/ epoch > 1, it is entirely up to the application to handle this in the way it deems most secure and performant.

I will try to use the epoch design currently being worked on in the SDK.  

One way, there is an epoch module that tracks epochs and changes them accordingly. The value of how many blocks is considered to be an epoch would be changed from a module param to a consensus param. When a param proposal to change the param is made it would be a consensus param change instead of a module level param change. 

Is this what you meant?

**Comment by marbar3778** [comment]
> What is the envisioned interface to the applications regarding punishment. Is punishment happening within epochs? Is it in the responsibility of the applications to figure out the validator set has changed due to misbehavior?

This wouldn't be a concern of Tendermint as we currently don't care of the application handles evidence or how they handle it. We would handle evidence and report it in the same manner as now. This leads to the least amount of changes in Tendemrint. This is how I envision it, I could be missing something?

**Comment by cmwaters** [comment]
When you punish someone you kind of want their validator power to change immediately and not wait until the next epoch to take affect else they could continue to wreck havoc

**Comment by cmwaters** [comment]
This epoch system, would it be purely for validator set updates or also for consensus param updates?

**Comment by marbar3778** [comment]
> When you punish someone you kind of want their validator power to change immediately and not wait until the next epoch to take affect else they could continue to wreck havoc

We don't have a way to enforce this. The best we can do is recommend how to do something. 

> This epoch system, would it be purely for validator set updates or also for consensus param updates?

I think the consensus param update could only happen at the end of an epoch otherwise tendermint will need to make assumptions on how to handle the overlap.

**Comment by cmwaters** [comment]
> We don't have a way to enforce this. The best we can do is recommend how to do handle evidence

You're right that tendermint doesn't do this but I think it's fairly safe to say that applications will want this. For example, if the epoch is 1 day and after 12 hours someone double votes, the application will want to immediately change the validator set. If we only allowed changes to happen at the turn of the epoch, then the network would have to wait 12 more hours until the voting power could be changed.

**Comment by marbar3778** [comment]
> You're right that tendermint doesn't do this but I think it's fairly safe to say that applications will want this. For example, if the epoch is 1 day and after 12 hours someone double votes, the application will want to immediately change the validator set. If we only allowed changes to happen at the turn of the epoch, then the network would have to wait 12 more hours until the voting power could be changed.

We can say in Tendermint we expect validator set changes to occur this often (epoch_duration) but we don't prohibit the change within an epoch. In the SDK I believe it is also being left up to the implementation and not set in stone.

**Comment by alexanderbez** [comment]
Yeah I don't think we need to overcomplicate this. I don't think there is any necessity of any sort of new module or even to handle any kind of evidence. It's entirely up to the application to handle epochs in `x/staking`. I believe in Tendermint we can just simply ignore any changes during the epoch.

If the application decides to send updates within the epoch, then that is a sign of a faulty application. We can either panic or log & ignore?

**Comment by josef-widder** [comment]
I had a quick look at the ADR. I didn't find heights mentioned. What is the relationship between epochs and heights?

**Comment by alexanderbez** [comment]
I believe epochs map directly to heights, e.g. epoch = 1000, then validators and powers are buffered for 1000 blocks and applied at the end of the epoch, i.e. at heights H % 1000 == 0.

**Comment by cmwaters** [comment]
> I believe in Tendermint we can just simply ignore any changes during the epoch.

Yeah I disagree with this. Although Tendermint doesn't decide the extent of the punishment it should still make accessible the tools to allow the application to punish malicious validators. In a system where tendermint ignores validator set updates within epochs, applications are incapable of exercising punishment for that duration. This means that a malicious cabal of validators could continuously attack the network for the entire period of the epoch without retribution. 

I think that epochs are elements that should be implemented purely on the application side

**Comment by alexanderbez** [comment]
> Although Tendermint doesn't decide the extent of the punishment it should still make accessible the tools to allow the application to punish malicious validators.

How? For starters, the application would halt due to merkle root mismatch. So if there exists a cabal, they would be operating on a fork. How and who would you punish?

**Comment by marbar3778** [comment]
> Although Tendermint doesn't decide the extent of the punishment it should still make accessible the tools to allow the application to punish malicious validators.

Sending evidence to the app from Tendermint is done immediately when it's witnessed, this does not change. If the app wants to change the validator set they can, we don't have to limit it. This proposal is meant to help with light clients and possibly how storage of validator sets are handled internally.

**Comment by cmwaters** [comment]
@alexanderbez not all attacks are forks. Even if a validator had less than 1/3 voting power it could spam the network with evidence causing very little txs to pass through until the end of the epoch where it then gets replaced. If the cabal was greater than 1/3 it could continue to attempt to attack the light client long after. In the case of attacks with higher power, malicious validators could sustain both sides of the forks knowing that they would still have power to hold the forks and arbitrate over the difference in transactions.

In any case, the main reason I think that epochs should be implemented on the application or cosmos sdk instead of tendermint is because tendermint will benefit from an epoch system without having to be explicit about it. Validator set changes that occur irregularly will automatically help quicken light client verification without needing to specify exactly when these epochs are. Validator sets are only "really" stored when they change which means they would already benefit from an epoch system without indicating when exactly the epochs are.

Also the problem with being explicit about epochs in tendermint is that if they are a consensus parameter, they can be changed dynamically which means one epoch could be one week and the next one could be one hour. This variance means that there's very little we can optimise for than what is already in place

**Comment by alexanderbez** [comment]
To be honest, I'm a bit lost here. The only main issue here is there could be an app hash divergence. Correct me if I'm wrong though.

**Comment by cmwaters** [comment]
How do you think there would be an app hash divergence?

**Comment by alexanderbez** [comment]
Because a sub-set of the validators, which are malicious, decide to provide validator set updates within the epoch while the others do not. This, AFAIK, is the entire crux of the issue you're describing.

**Comment by cmwaters** [comment]
Okay yeah we sort of of diverged a bit. I was meaning that in the event of an attack where evidence is produced, an application will want to have the ability to change the power of the validators as a **response** to the misbehaviour. I wasn't meaning that the attack itself might be to change the validator set during the middle of an epoch which wouldn't really work.

**Comment by cmwaters** [comment]
Anyway the main idea I'm trying to get across is that Tendermint is already pretty well equipped for applications that use an epoch system without being explicit as to the actual duration of an epoch to Tendermint

**Comment by ValarDragon** [comment]
Personally, I think the main reason to have Tendermint be aware of an epoch'd power-change parameter is to have lite client bisection's base case automatically benefit from this. Granted improving the base case of bisection is almost surely a micro-optimization. (I actually flipped on my view of this recently, I used to think it was much more impactful)

I don't see how lite clients will be able to benefit from a larger epoch, if only the application is aware of the new epoch.

> @marbar3778 I support this idea, but I would like to know the interplay between this new field and the application. Specifically, in order to handle epoch-based staking, w/ epoch > 1, it is entirely up to the application to handle this in the way it deems most secure and performant.
> 
> Can you describe the interplay between this field and say how an x/staking module would use it?

I view the way it would happen as the epoch'd staking application just tells Tendermint what the epoch_duration parameter is. Then the tendermint lite client optionally can take in an epoch duration / base case number of blocks, and it sets it to 1 if the epoch duration isn't available. If the stake weights change during the middle of an epoch, Tendermint would ignore it, and return an error to the application. 

I'm not sure if this is short term worth the code complexity for it, since improving the bisection algorithm imo isn't important near-term relative to other optimizations. (The bisection base case is only ever hit if the weighted set difference of validator power is very high)

**Comment by josef-widder** [comment]
OK, looking again at the initial discussions, it looks like epochs are primarily a concern for the staking module. So in principle epoch durations seems to be application data to me. 

Since potential light client optimizations seem then to be dependent on how the application chooses to handle slashing in the middle of epochs (and there might some liveness issues), and design choices seem unclear, I don't see immediate need for this. (Again, it is always possible to adapt a light client to be application specific in the choice of pivot point for bisection in order to gain some performance.)

So to me `epoch_duration` really looks like application data. Not sure why it should be in `BlockParams`.

**Comment by cmwaters** [comment]
Stale bot closed this issue. Do we want to reopen it again. Do we still think this is a valid proposal we may want to pursue or did we come to a verdict already?

**Comment by alexanderbez** [comment]
I agree with @josef-widder here @cmwaters

**Comment by cmwaters** [comment]
I would also agree. wdyt @marbar3778?
