### ISSUE TITLE
Code/spec discrepancies to Lightclient in Go

### ISSUE THREAD

**Issue by josef-widder** [tendermint/spec#294]
Surfaced from [Informal Systems](https://informal.systems/) Evidence end-to-end audit of https://github.com/tendermint/tendermint/commit/5a39f72aa8288696d7284e56e3f630ab721a9f9a.

We found the following code/spec discrepancies, which should be addressed:

1. [Lightblock](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/types/light.go#L13) differs from [spec](https://github.com/tendermint/spec/blob/master/spec/light-client/verification/verification_002_draft.md#lcv-data-lightblock1). Missing
     - NextValidators
     - Provider

2. The verification [trace](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/light/client.go#L740)  is computed and then thrown away in the implementation, while in the specification is stored.

3. It seems that a commit with [multiple signatures for the same validator](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/types/validator_set.go#L808)  possible in the implementation. In the specification a commit is a set. Should a check for double signatures be a part of basic validation?

4. [evidence generation](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/light/detector.go#L243)   differs from specification. `CommonHeight` depends on type in the  implementation. This is not the case in the spec. As a result  validation on-chain differs from the spec.
   
5. [Byzantine  validators](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/light/detector.go#L252) is computed by the light client in the implementation but not in the  specification.
   
6. [Time](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/light/detector.go#L249) is computed by the lightnode, while in the specification evidence does not have a time field.

**Comment by cmwaters** [comment]
> Lightblock differs from spec. Missing NextValidators and Provider.

So both Anton and I agreed for the implementation that light blocks don't need to include the current validator set and the next validator set: one of the two is sufficient and having both is just unnecessary bandwidth. We went with using the current validator set because it's gentler on the mental model as both signed header and validator set are all for the same height. 

That being said, there is a case to use the next validator set as this would allow us to remove `ValidatorHash` from the header and just have `NextValidatorsHash` so we could make this transition if there is enough support for it.

> The verification trace is computed and then thrown away in the implementation, while in the specification is stored.

The tradeoff I see here is that keeping the trace is kind of like having a lot of cache and will allow for quicker verification of future blocks that are within the trace range. However, light clients might not find that valuable and may prefer remaining **light** (that being said headers are extremely small and we do prune). I was thinking we could make this an option for operators to choose whether they want to persist the trace or not

> It seems that a commit with multiple signatures for the same validator possible in the implementation. In the specification a commit is a set. Should a check for double signatures be a part of basic validation?

Yes definitely. The `commit` in the implementation is an array of `commit_sigs`. This is more efficient because we can use the validator index to infer which commit belongs to who. 

> evidence generation differs from specification. CommonHeight depends on type in the implementation. This is not the case in the spec. As a result validation on-chain differs from the spec.

I think we should use `CommonHeight` as a means of determining evidence type. It's far quicker than having to compare hashes in the header. Could you point me to where I would need to update the spec.

> Byzantine validators is computed by the light client in the implementation but not in the specification.

This is because the specification never mentions the ABCI boundary which is an important consideration for the implementation. Maybe we'd want to add a section about ABCI and the information that we send across to the application. 

> Time is computed by the lightnode, while in the specification evidence does not have a time field.

Evidence in the spec now is updated to include the timestamp (along with other ABCI relevant information)
https://github.com/tendermint/spec/blob/master/spec/core/data_structures.md#lightclientattackevidence

**Comment by cmwaters** [comment]
> Byzantine validators is computed by the light client in the implementation but not in the specification.

Thinking about this again. The light client doesn't need to verify the byzantine validators and add them to the evidence since the node should do it themselves anyway
